# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: SSH@0
    inputs:
      sshEndpoint: 'CFBot Deployer'
      runOptions: 'inline'
      inline: |
        cd /home/cpadmin/CFBot/
        sudo git pull
        sudo /home/cpadmin/.nvm/versions/node/v14.8.0/bin/node /home/cpadmin/.nvm/versions/node/v14.8.0/lib/node_modules/npm/bin/npm-cli.js
        sudo systemctl restart cfbot.service
      readyTimeout: '20000'
      failOnStderr: false
    displayName: 'Deploy'
